import "../css/reset.css";

import { figTree } from "@/fonts/fonts";
import type { Metadata } from "next";
import "../css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={figTree.className}>
        {children}
      </body>
    </html>
  );
}
